title: "Polonsky / Brine Digital Humanities Internships Summer 2020"

baseurl: ""
resource_prefix: "resources/"
github_username: jversoza
slides_lib: "../../resources/lib"

markdown: kramdown
kramdown:
  entity_output: numeric
  smart_quotes: apos,apos,quot,quot
permalink: none
exclude: [bower_components, README.md, bower.json, gruntfile.js, node_modules]

vars:
  survey_github: ""
  piazza: "https://piazza.com/"
  email: "jversoza at cs dot nyu dot edu"
  slides_img_prefix: "../../resources/img"
  
  # course
  course_number: "Polonsky / Brine"
  course_section: "001"
  course_name: "Digital Humanities Internships"
  course_semester: "Summer 2020"
  course_time: "T and TH, 12:30PM-1:45PM"
  course_room: "Silv 411"
  course_site: https://cs.nyu.edu/courses/spring20/CSCI-UA.0479-001/ 
  course_site_alt: http://cs.nyu.edu/~jversoza
  
  # office hours
  office_hours: "<br>TBD"
  office_hours_room: WWH 422
  
  # midterm
  midterm1_date: "N/A"
  midterm1_time: "N/A"
  
  # finals
  final_date: "N/A"
  final_time: "N/A"
  final_room: "N/A"
  
  
#  book1: "Python for Data Analysis Book, 2nd Edition"
#  book1_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/python-for-data/9781491957653/"
#  book1_author: "Wes McKinney"
#
#  book2: "Practical SQL"
#  book2_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/practical-sql/9781492067580/"
#  book2_author:  "Anthony DeBarros"
#  
#  book3: "Think Stats"
#  book3_link: "http://greenteapress.com/thinkstats/"
#  book3_author: "Allen B. Downey"
#
#  book4: "Data Science from Scratch, 2nd Edition"
#  book4_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/data-science-from/9781492041122/"
#  book4_author: "Joel Grus"
#  
#  book5: "Relational Database Design and Implementation, 3rd Edition"
#  book5_link: "https://learning-oreilly-com.proxy.library.nyu.edu/library/view/relational-database-design/9780123747303/"
#  book5_author: "Jan L. Harrington"


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: Your awesome title
# email: your-email@example.com
# description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
